In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('archive (2)/genai_llm_usage_dataset_1000.csv')

In [4]:
df.head

<bound method NDFrame.head of      session_id  model_name application_domain       task_type  prompt_length  \
0             1      GPT-4o         Healthcare   Summarization           1319
1             2      GPT-4o   Customer Support   Summarization            486
2             3     Gemma 3             Retail  Classification           1439
3             4     Gemma 3             Retail   Summarization           1662
4             5     Gemma 3            Finance  Classification           1452
..          ...         ...                ...             ...            ...
995         996   Llama 3.1             Retail              QA            696
996         997    Qwen 2.5            Finance             RAG            227
997         998  Claude 3.7   Customer Support              QA           1571
998         999   Llama 3.1   Customer Support  Classification           1253
999        1000  Claude 3.7         Healthcare  Classification            482

     total_tokens  temperature  top_p  rag_enabled  latency_sec  \
0            2455         0.17   0.87            0         3.76
1            1425         0.76   0.51            0         2.36
2            1648         0.63   0.64            0         3.68
3            2812         0.07   0.73            0         3.25
4            1678         0.10   0.83            0         8.04
..            ...          ...    ...          ...          ...
995          1044         1.46   0.95            0         3.99
996          1022         0.91   0.90            0         4.47
997          2694         1.50   0.54            1         2.77
998          2451         0.71   0.76            0         5.21
999          1341         0.68   0.87            1         1.70

     hallucination_flag  user_satisfaction  estimated_cost_usd  \
0                     0                  4              0.0236
1                     1                  5              0.0236
2                     1                  4              0.0139
3                     1                  4              0.0374
4                     0                  4              0.0171
..                  ...                ...                 ...
995                   1                  4              0.0076
996                   1                  5              0.0026
997                   0                  5              0.0465
998                   1                  4              0.0157
999                   0                  5              0.0112

     successful_response
0                      1
1                      0
2                      0
3                      0
4                      0
..                   ...
995                    0
996                    0
997                    1
998                    0
999                    1

[1000 rows x 14 columns]>

In [5]:
df.isna().sum()

session_id             0
model_name             0
application_domain     0
task_type              0
prompt_length          0
total_tokens           0
temperature            0
top_p                  0
rag_enabled            0
latency_sec            0
hallucination_flag     0
user_satisfaction      0
estimated_cost_usd     0
successful_response    0
dtype: int64

In [6]:
df.describe

<bound method NDFrame.describe of      session_id  model_name application_domain       task_type  prompt_length  \
0             1      GPT-4o         Healthcare   Summarization           1319
1             2      GPT-4o   Customer Support   Summarization            486
2             3     Gemma 3             Retail  Classification           1439
3             4     Gemma 3             Retail   Summarization           1662
4             5     Gemma 3            Finance  Classification           1452
..          ...         ...                ...             ...            ...
995         996   Llama 3.1             Retail              QA            696
996         997    Qwen 2.5            Finance             RAG            227
997         998  Claude 3.7   Customer Support              QA           1571
998         999   Llama 3.1   Customer Support  Classification           1253
999        1000  Claude 3.7         Healthcare  Classification            482

     total_tokens  temperature  top_p  rag_enabled  latency_sec  \
0            2455         0.17   0.87            0         3.76
1            1425         0.76   0.51            0         2.36
2            1648         0.63   0.64            0         3.68
3            2812         0.07   0.73            0         3.25
4            1678         0.10   0.83            0         8.04
..            ...          ...    ...          ...          ...
995          1044         1.46   0.95            0         3.99
996          1022         0.91   0.90            0         4.47
997          2694         1.50   0.54            1         2.77
998          2451         0.71   0.76            0         5.21
999          1341         0.68   0.87            1         1.70

     hallucination_flag  user_satisfaction  estimated_cost_usd  \
0                     0                  4              0.0236
1                     1                  5              0.0236
2                     1                  4              0.0139
3                     1                  4              0.0374
4                     0                  4              0.0171
..                  ...                ...                 ...
995                   1                  4              0.0076
996                   1                  5              0.0026
997                   0                  5              0.0465
998                   1                  4              0.0157
999                   0                  5              0.0112

     successful_response
0                      1
1                      0
2                      0
3                      0
4                      0
..                   ...
995                    0
996                    0
997                    1
998                    0
999                    1

[1000 rows x 14 columns]>

In [7]:
df.describe()

,session_id,prompt_length,total_tokens,temperature,top_p,rag_enabled,latency_sec,hallucination_flag,user_satisfaction,estimated_cost_usd,successful_response
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1022.780000,1636.763000,0.74728,0.74207,0.502000,5.368310,0.507000,4.345000,0.018026,0.202000
std,288.819436,574.062391,681.390085,0.42545,0.14234,0.500246,2.375312,0.500201,0.581647,0.011971,0.401693
min,1.000000,12.000000,71.000000,0.00000,0.50000,0.000000,0.310000,0.000000,3.000000,0.000500,0.000000
25%,250.750000,520.750000,1118.000000,0.37000,0.62000,0.000000,3.300000,0.000000,4.000000,0.008400,0.000000
50%,500.500000,1056.000000,1635.500000,0.74000,0.74000,1.000000,5.460000,1.000000,4.000000,0.015400,0.000000
75%,750.250000,1493.250000,2142.250000,1.11000,0.86000,1.000000,7.370000,1.000000,5.000000,0.024900,0.000000
max,1000.000000,2000.000000,3158.000000,1.50000,1.00000,1.000000,10.440000,1.000000,5.000000,0.060300,1.000000

In [8]:
df.describe(include="object")

C:\Users\Administrator\AppData\Local\Temp\ipykernel_23640\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

           model_name application_domain task_type
count            1000               1000      1000
unique              6                  7         6
top     Mistral Large   Customer Support       RAG
freq              193                165       180

In [9]:
rows, columns = df.shape
output = f"The dataset has {rows} rows and {columns} columns."
print(output)

The dataset has 1000 rows and 14 columns.